version: '3.5'

# if colima dies on mac, start with: colima start --mount-type 9p 
# in order to avoid local file permissions

# psql postgresql://limes:pass123@localhost:5432/limes

services:
  app:
    build:
      context: ./limes    
    ports:
      - "3000:80"
    links:
      - db
      - backend
    restart: unless-stopped
    networks:
      - limes-network
  backend:
    build:
      context: ./server
    environment:
      - DATABASE_ADDRESS=db
    ports:
      - "3001:3001"
    networks:
      - limes-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: limes
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: limes
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - limes-network
networks:
  limes-network:
