# Use the official Python image as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the entire Flask app to the working directory
COPY . .

# Expose port 5000 to serve the app
EXPOSE 30003

# Start the Flask server
# CMD ["sh", "-c", "./server/prod_run.sh"]