# build stage
FROM node:14

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# serve stage
FROM nginx:alpine

# get files and nginx conf from build stage
COPY --from=0 /app/build /usr/share/nginx/html
COPY --from=0 /app/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]